spring:
  application:
    name: courier-management
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/courierdb
    username: postgres
    password: postgres-server
    driver-class-name: org.postgresql.Driver
server.port: 8081