spring:
  application:
    name: delivery-tracking
  datasource:
    url: jdbc:postgresql://localhost:5432/deliverydb
    username: postgres
    password: postgres-server
    driver-class-name: org.postgresql.Driver
server:
  port: 8080